name: spring-outbox-example
services:
  outbox-producer-app:
    container_name: outbox-producer-app
    build:
      context: ..
      dockerfile: ./spring-outbox-example/spring-outbox-producer-example/Dockerfile
    image: outbox-producer-app
    depends_on:
      - outbox-producer-postgresql
    environment:
      OUTBOX_PUBLISHER_SENDER_TYPE: kafka     # or rabbit_mq
    ports:
      - "8080:8080"

  outbox-producer-postgresql:
    container_name: outbox-producer-postgresql
    image: postgres:18-alpine
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: outbox_example
    ports:
      - "5432:5432"

  outbox-consumer-app:
    container_name: outbox-consumer-app
    build:
      context: ..
      dockerfile: ./spring-outbox-example/spring-outbox-consumer-example/Dockerfile
    image: outbox-consumer-app
    depends_on:
      - outbox-consumer-postgresql
      - outbox-consumer-redis
    environment:
      SPRING_PROFILES_ACTIVE: kafka     # or rabbitmq
    ports:
      - "8081:8080"

  outbox-consumer-postgresql:
    container_name: outbox-consumer-postgresql
    image: postgres:18-alpine
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: outbox_example
    ports:
      - "5433:5432"

  outbox-consumer-redis:
    container_name: outbox-consumer-redis
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  outbox-traffic-generator-app:
    container_name: outbox-traffic-generator-app
    build:
      context: ..
      dockerfile: ./spring-outbox-example/spring-outbox-traffic-generator/Dockerfile
    image: outbox-traffic-generator-app
    depends_on:
      - outbox-producer-app
    ports:
      - "8082:8080"

  outbox-kafka:
    container_name: outbox-kafka
    image: bitnami/kafka:latest
    profiles: [ "kafka" ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://outbox-kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@outbox-kafka:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/bitnami/kafka/data

  outbox-rabbitmq:
    container_name: outbox-rabbitmq
    image: rabbitmq:3-management
    profiles: [ "rabbitmq" ]
    ports:
      - "5672:5672"
      - "15672:15672"

  outbox-prometheus:
    container_name: outbox-prometheus
    image: prom/prometheus:latest
    depends_on:
      - outbox-producer-app
      - outbox-consumer-app
    networks:
      - default
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  outbox-grafana:
    container_name: outbox-grafana
    image: grafana/grafana:latest
    depends_on:
      - outbox-prometheus
    networks:
      - default
    ports:
      - "3000:3000"

volumes:
  kafka_data: {}