version: "3.8"
name: spring-outbox-example
services:

#  producer-app:
#    container_name: outbox-example-producer-app
#    build:
#      context: ..
#      dockerfile: spring-outbox-example/spring-outbox-publisher-example/Dockerfile
#    image: outbox-producer-app
#    ports:
#      - "8080:8080"

  producer-postgresql:
    container_name: outbox-example-producer-postgresql
    image: postgres:18-alpine
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: outbox_example
    ports:
      - "5432:5432"

#  consumer-app:
#    container_name: outbox-example-consumer-app
#    build:
#      context: ..
#      dockerfile: spring-outbox-example/spring-outbox-consumer-example/Dockerfile
#    image: outbox-consumer-app
#    ports:
#      - "8081:8080"

  consumer-postgresql:
    container_name: outbox-example-consumer-postgresql
    image: postgres:18-alpine
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: outbox_example
    ports:
      - "5433:5432"

  redis:
    container_name: outbox-example-redis
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

  kafka:
    container_name: outbox-example-kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/bitnami/kafka/data

  prometheus:
    container_name: outbox-prometheus
    image: prom/prometheus:latest
    networks:
      - default
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: outbox-grafana
    image: grafana/grafana:latest
    networks:
      - default
    ports:
      - "3000:3000"

volumes:
  kafka_data: {}