scrape_configs:
  - job_name: 'outbox-publisher'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'outbox-consumer'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']