spring:
  application:
    name: spring-outbox-example
  datasource:
    url: jdbc:postgresql://consumer-postgresql:5433/outbox_example
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  data:
    redis:
      port: 6379
      host: consumer-redis
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8080
outbox:
  thread-pool-size: 2
  publisher:
    enabled: false
  consumer:
    enabled: true
    clean-up:
      enabled: true
      ttl: 24h
    cache:
      enabled: true
      cache-name: "outbox:consumed"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true