spring:
  application:
    name: spring-outbox-example
  profiles:
    active: kafka     # or rabbitmq
  datasource:
    url: jdbc:postgresql://consumer-postgresql:5432/outbox_example
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  data:
    redis:
      port: 6379
      host: consumer-redis
server:
  port: 8080
outbox:
  thread-pool-size: 2
  publisher:
    enabled: false
  consumer:
    enabled: true
    clean-up:
      enabled: true
      ttl: 24h
    cache:
      enabled: true
      cache-name: "outbox:consumed"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true